# REV01 Sun Jun  7 2020

CC='gcc'
CFLAGS='-std=c99'
 
P00=w10a-iofile1
P01=w10b-iofile2

EXECS= \
	$(P00)  \
	$(P01)  \

OFILES=\
	output_problem_a.txt \
	output_problem_b1.txt \
	output_problem_b2.txt \

all:	$(EXECS)

clean:
	rm -f $(EXECS)
	rm -f $(OFILES)

